# Generated by Django 4.2 on 2023-10-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gym',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorisation.gym'),
        ),
    ]
